// Code generated by protoc-gen-go. DO NOT EDIT.
// source: context.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/lyft/protoc-gen-validate/validate"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListString struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListString) Reset()         { *m = ListString{} }
func (m *ListString) String() string { return proto.CompactTextString(m) }
func (*ListString) ProtoMessage()    {}
func (*ListString) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{0}
}

func (m *ListString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListString.Unmarshal(m, b)
}
func (m *ListString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListString.Marshal(b, m, deterministic)
}
func (m *ListString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListString.Merge(m, src)
}
func (m *ListString) XXX_Size() int {
	return xxx_messageInfo_ListString.Size(m)
}
func (m *ListString) XXX_DiscardUnknown() {
	xxx_messageInfo_ListString.DiscardUnknown(m)
}

var xxx_messageInfo_ListString proto.InternalMessageInfo

func (m *ListString) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Context2 struct {
	Custom               map[string][]byte    `protobuf:"bytes,1,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Response             *Context2_Response   `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Request              *Context2_Request    `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Tags                 map[string]*TagValue `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	User                 *User                `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Page                 *Context2_Page       `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	Service              *Service             `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Context2) Reset()         { *m = Context2{} }
func (m *Context2) String() string { return proto.CompactTextString(m) }
func (*Context2) ProtoMessage()    {}
func (*Context2) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{1}
}

func (m *Context2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2.Unmarshal(m, b)
}
func (m *Context2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2.Marshal(b, m, deterministic)
}
func (m *Context2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2.Merge(m, src)
}
func (m *Context2) XXX_Size() int {
	return xxx_messageInfo_Context2.Size(m)
}
func (m *Context2) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2.DiscardUnknown(m)
}

var xxx_messageInfo_Context2 proto.InternalMessageInfo

func (m *Context2) GetCustom() map[string][]byte {
	if m != nil {
		return m.Custom
	}
	return nil
}

func (m *Context2) GetResponse() *Context2_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Context2) GetRequest() *Context2_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Context2) GetTags() map[string]*TagValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Context2) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Context2) GetPage() *Context2_Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *Context2) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type Context2_Page struct {
	Referer              string   `protobuf:"bytes,1,opt,name=referer,proto3" json:"referer,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context2_Page) Reset()         { *m = Context2_Page{} }
func (m *Context2_Page) String() string { return proto.CompactTextString(m) }
func (*Context2_Page) ProtoMessage()    {}
func (*Context2_Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{1, 0}
}

func (m *Context2_Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2_Page.Unmarshal(m, b)
}
func (m *Context2_Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2_Page.Marshal(b, m, deterministic)
}
func (m *Context2_Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2_Page.Merge(m, src)
}
func (m *Context2_Page) XXX_Size() int {
	return xxx_messageInfo_Context2_Page.Size(m)
}
func (m *Context2_Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Context2_Page proto.InternalMessageInfo

func (m *Context2_Page) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *Context2_Page) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Context2_Request struct {
	Body                 []byte                   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Env                  map[string][]byte        `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Headers              map[string]*ListString   `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HttpVersion          string                   `protobuf:"bytes,4,opt,name=http_version,json=httpVersion,proto3" json:"http_version,omitempty"`
	Method               string                   `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Socket               *Context2_Request_Socket `protobuf:"bytes,6,opt,name=socket,proto3" json:"socket,omitempty"`
	Url                  *Context2_Request_Url    `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Cookies              map[string][]byte        `protobuf:"bytes,8,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Context2_Request) Reset()         { *m = Context2_Request{} }
func (m *Context2_Request) String() string { return proto.CompactTextString(m) }
func (*Context2_Request) ProtoMessage()    {}
func (*Context2_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{1, 1}
}

func (m *Context2_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2_Request.Unmarshal(m, b)
}
func (m *Context2_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2_Request.Marshal(b, m, deterministic)
}
func (m *Context2_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2_Request.Merge(m, src)
}
func (m *Context2_Request) XXX_Size() int {
	return xxx_messageInfo_Context2_Request.Size(m)
}
func (m *Context2_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Context2_Request proto.InternalMessageInfo

func (m *Context2_Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Context2_Request) GetEnv() map[string][]byte {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Context2_Request) GetHeaders() map[string]*ListString {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Context2_Request) GetHttpVersion() string {
	if m != nil {
		return m.HttpVersion
	}
	return ""
}

func (m *Context2_Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Context2_Request) GetSocket() *Context2_Request_Socket {
	if m != nil {
		return m.Socket
	}
	return nil
}

func (m *Context2_Request) GetUrl() *Context2_Request_Url {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *Context2_Request) GetCookies() map[string][]byte {
	if m != nil {
		return m.Cookies
	}
	return nil
}

type Context2_Request_Socket struct {
	Encrypted            bool     `protobuf:"varint,1,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	RemoteAddress        string   `protobuf:"bytes,2,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context2_Request_Socket) Reset()         { *m = Context2_Request_Socket{} }
func (m *Context2_Request_Socket) String() string { return proto.CompactTextString(m) }
func (*Context2_Request_Socket) ProtoMessage()    {}
func (*Context2_Request_Socket) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{1, 1, 0}
}

func (m *Context2_Request_Socket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2_Request_Socket.Unmarshal(m, b)
}
func (m *Context2_Request_Socket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2_Request_Socket.Marshal(b, m, deterministic)
}
func (m *Context2_Request_Socket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2_Request_Socket.Merge(m, src)
}
func (m *Context2_Request_Socket) XXX_Size() int {
	return xxx_messageInfo_Context2_Request_Socket.Size(m)
}
func (m *Context2_Request_Socket) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2_Request_Socket.DiscardUnknown(m)
}

var xxx_messageInfo_Context2_Request_Socket proto.InternalMessageInfo

func (m *Context2_Request_Socket) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *Context2_Request_Socket) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

type Context2_Request_Url struct {
	Raw                  string   `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Protocol             string   `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Full                 string   `protobuf:"bytes,3,opt,name=full,proto3" json:"full,omitempty"`
	Hostname             string   `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Pathname             string   `protobuf:"bytes,6,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Search               string   `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	Hash                 string   `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context2_Request_Url) Reset()         { *m = Context2_Request_Url{} }
func (m *Context2_Request_Url) String() string { return proto.CompactTextString(m) }
func (*Context2_Request_Url) ProtoMessage()    {}
func (*Context2_Request_Url) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{1, 1, 1}
}

func (m *Context2_Request_Url) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2_Request_Url.Unmarshal(m, b)
}
func (m *Context2_Request_Url) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2_Request_Url.Marshal(b, m, deterministic)
}
func (m *Context2_Request_Url) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2_Request_Url.Merge(m, src)
}
func (m *Context2_Request_Url) XXX_Size() int {
	return xxx_messageInfo_Context2_Request_Url.Size(m)
}
func (m *Context2_Request_Url) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2_Request_Url.DiscardUnknown(m)
}

var xxx_messageInfo_Context2_Request_Url proto.InternalMessageInfo

func (m *Context2_Request_Url) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

func (m *Context2_Request_Url) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Context2_Request_Url) GetFull() string {
	if m != nil {
		return m.Full
	}
	return ""
}

func (m *Context2_Request_Url) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Context2_Request_Url) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Context2_Request_Url) GetPathname() string {
	if m != nil {
		return m.Pathname
	}
	return ""
}

func (m *Context2_Request_Url) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *Context2_Request_Url) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Context2_Response struct {
	Finished             bool                   `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	Headers              map[string]*ListString `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HeadersSent          bool                   `protobuf:"varint,3,opt,name=headers_sent,json=headersSent,proto3" json:"headers_sent,omitempty"`
	StatusCode           uint32                 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Context2_Response) Reset()         { *m = Context2_Response{} }
func (m *Context2_Response) String() string { return proto.CompactTextString(m) }
func (*Context2_Response) ProtoMessage()    {}
func (*Context2_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{1, 2}
}

func (m *Context2_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2_Response.Unmarshal(m, b)
}
func (m *Context2_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2_Response.Marshal(b, m, deterministic)
}
func (m *Context2_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2_Response.Merge(m, src)
}
func (m *Context2_Response) XXX_Size() int {
	return xxx_messageInfo_Context2_Response.Size(m)
}
func (m *Context2_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Context2_Response proto.InternalMessageInfo

func (m *Context2_Response) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *Context2_Response) GetHeaders() map[string]*ListString {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Context2_Response) GetHeadersSent() bool {
	if m != nil {
		return m.HeadersSent
	}
	return false
}

func (m *Context2_Response) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*ListString)(nil), "model.ListString")
	proto.RegisterType((*Context2)(nil), "model.Context2")
	proto.RegisterMapType((map[string][]byte)(nil), "model.Context2.CustomEntry")
	proto.RegisterMapType((map[string]*TagValue)(nil), "model.Context2.TagsEntry")
	proto.RegisterType((*Context2_Page)(nil), "model.Context2.Page")
	proto.RegisterType((*Context2_Request)(nil), "model.Context2.Request")
	proto.RegisterMapType((map[string][]byte)(nil), "model.Context2.Request.CookiesEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "model.Context2.Request.EnvEntry")
	proto.RegisterMapType((map[string]*ListString)(nil), "model.Context2.Request.HeadersEntry")
	proto.RegisterType((*Context2_Request_Socket)(nil), "model.Context2.Request.Socket")
	proto.RegisterType((*Context2_Request_Url)(nil), "model.Context2.Request.Url")
	proto.RegisterType((*Context2_Response)(nil), "model.Context2.Response")
	proto.RegisterMapType((map[string]*ListString)(nil), "model.Context2.Response.HeadersEntry")
}

func init() { proto.RegisterFile("context.proto", fileDescriptor_b64063be2fc89884) }

var fileDescriptor_b64063be2fc89884 = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0x96, 0x3d, 0x63, 0x7b, 0x5c, 0xb6, 0x03, 0xb4, 0x22, 0xa5, 0x99, 0x44, 0x89, 0xb1, 0x58,
	0xf0, 0x65, 0x8d, 0x70, 0x50, 0x04, 0x39, 0x80, 0xc0, 0x8a, 0x94, 0x03, 0x91, 0x50, 0x3b, 0x9b,
	0xab, 0xd5, 0x3b, 0x53, 0xeb, 0x19, 0xed, 0x78, 0xda, 0x74, 0xb7, 0x0d, 0xbe, 0xf1, 0x0e, 0x3c,
	0x0a, 0x17, 0xc4, 0x89, 0xd7, 0xe1, 0x15, 0x38, 0xa1, 0xfe, 0x19, 0xff, 0xad, 0x8d, 0xb4, 0x52,
	0x6e, 0xd5, 0x55, 0xdf, 0xd7, 0xf3, 0xd5, 0x5f, 0x0f, 0xf4, 0x12, 0x51, 0x6a, 0xfc, 0x55, 0x8f,
	0x96, 0x52, 0x68, 0x41, 0x1a, 0x0b, 0x91, 0x62, 0x11, 0x3f, 0x5a, 0xf3, 0x22, 0x4f, 0xb9, 0xc6,
	0x2f, 0x2a, 0xc3, 0xc5, 0xe3, 0x9e, 0x42, 0xb9, 0xce, 0x93, 0xea, 0x08, 0x9a, 0xcf, 0x55, 0x65,
	0xaf, 0x14, 0x4a, 0x67, 0x0f, 0x06, 0x00, 0x3f, 0xe6, 0x4a, 0x4f, 0xb5, 0xcc, 0xcb, 0x39, 0x79,
	0x08, 0x8d, 0x35, 0x2f, 0x56, 0x48, 0x6b, 0xfd, 0x60, 0xd8, 0x66, 0xee, 0x30, 0xf8, 0xb3, 0x07,
	0xd1, 0xc4, 0x7d, 0x7c, 0x4c, 0x9e, 0x43, 0x33, 0x59, 0x29, 0x2d, 0x16, 0x16, 0xd3, 0x19, 0x3f,
	0x1e, 0x59, 0x21, 0xa3, 0x0a, 0x30, 0x9a, 0xd8, 0xe8, 0xab, 0x52, 0xcb, 0x0d, 0xf3, 0x50, 0xf2,
	0x15, 0x44, 0x12, 0xd5, 0x52, 0x94, 0x0a, 0x69, 0xbd, 0x5f, 0x1b, 0x76, 0xc6, 0xf4, 0x98, 0xc6,
	0x7c, 0x9c, 0x6d, 0x91, 0xe4, 0x4b, 0x68, 0x49, 0xfc, 0x79, 0x85, 0x4a, 0xd3, 0xc0, 0x92, 0x1e,
	0xdd, 0x25, 0xd9, 0x30, 0xab, 0x70, 0xe4, 0x12, 0x42, 0x93, 0x28, 0x0d, 0xad, 0xb6, 0x8f, 0x8f,
	0xf1, 0x6f, 0xf9, 0x5c, 0x39, 0x65, 0x16, 0x46, 0x9e, 0x41, 0x68, 0x6a, 0x41, 0x1b, 0xf6, 0xfa,
	0x8e, 0x87, 0x5f, 0x29, 0x94, 0xcc, 0x06, 0xc8, 0x10, 0xc2, 0x25, 0x9f, 0x23, 0x6d, 0x5a, 0xc0,
	0xc3, 0xe3, 0xfb, 0x7e, 0xe2, 0x73, 0x64, 0x16, 0x41, 0x86, 0xd0, 0xf2, 0x15, 0xa7, 0x2d, 0x0b,
	0x7e, 0xe0, 0xc1, 0x53, 0xe7, 0x65, 0x55, 0x38, 0x1e, 0x43, 0x68, 0x78, 0x84, 0x9a, 0xf4, 0x6e,
	0x50, 0xa2, 0xa4, 0xb5, 0x7e, 0x6d, 0xd8, 0x66, 0xd5, 0x91, 0x7c, 0x08, 0xc1, 0x4a, 0x16, 0xb6,
	0x52, 0x6d, 0x66, 0xcc, 0xf8, 0x8f, 0x16, 0xb4, 0x7c, 0xb2, 0x84, 0x40, 0x78, 0x2d, 0xd2, 0x8d,
	0x25, 0x75, 0x99, 0xb5, 0xc9, 0x18, 0x02, 0x2c, 0xd7, 0xb4, 0x6e, 0xd3, 0xee, 0x9f, 0x29, 0xd3,
	0xe8, 0x55, 0xb9, 0x76, 0xd9, 0x1b, 0x30, 0xf9, 0x16, 0x5a, 0x19, 0xf2, 0x14, 0xa5, 0xa2, 0x81,
	0xe5, 0x7d, 0x7a, 0x8e, 0xf7, 0xda, 0xc1, 0x1c, 0xb7, 0x22, 0x91, 0x4b, 0xe8, 0x66, 0x5a, 0x2f,
	0x67, 0x6b, 0x94, 0x2a, 0x17, 0x25, 0x0d, 0x8d, 0xdc, 0x1f, 0xe0, 0xaf, 0x7f, 0xfe, 0x0e, 0x1a,
	0x32, 0xa0, 0xbf, 0x45, 0xac, 0x63, 0xe2, 0xef, 0x5c, 0x98, 0x0c, 0xa0, 0xb9, 0x40, 0x9d, 0x89,
	0xd4, 0x56, 0xfb, 0x10, 0xe8, 0x23, 0xe4, 0x05, 0x34, 0x95, 0x48, 0x6e, 0x51, 0xfb, 0x82, 0x3f,
	0x3d, 0xa7, 0x68, 0x6a, 0x51, 0xcc, 0xa3, 0xc9, 0xa5, 0x2b, 0x98, 0x2b, 0xfc, 0xe3, 0x73, 0xa4,
	0x2b, 0x59, 0xd8, 0x6a, 0x9a, 0xcc, 0x13, 0x21, 0x6e, 0x73, 0x54, 0x34, 0xfa, 0xff, 0xcc, 0x27,
	0x0e, 0xe6, 0x33, 0xf7, 0xa4, 0xf8, 0x0d, 0x34, 0x9d, 0x00, 0xf2, 0x04, 0xda, 0x58, 0x26, 0x72,
	0xb3, 0xd4, 0x98, 0xda, 0x86, 0x44, 0x6c, 0xe7, 0x20, 0x17, 0xf0, 0x40, 0xe2, 0x42, 0x68, 0x9c,
	0xf1, 0x34, 0x95, 0xa8, 0x94, 0x6f, 0x69, 0xcf, 0x79, 0xbf, 0x77, 0xce, 0xf8, 0xf7, 0x3a, 0x04,
	0x57, 0xb2, 0x20, 0x4f, 0x20, 0x90, 0xfc, 0x17, 0x37, 0x0c, 0x07, 0xe5, 0x31, 0x6e, 0xf2, 0x19,
	0x44, 0x76, 0x65, 0x13, 0xe1, 0x27, 0xe3, 0x00, 0xb2, 0x8d, 0x91, 0xa7, 0x10, 0xde, 0xac, 0x8a,
	0xc2, 0xae, 0xcc, 0x21, 0xc6, 0xfa, 0xcd, 0x3d, 0x99, 0x50, 0xba, 0xe4, 0x0b, 0x3c, 0xd1, 0xb2,
	0x6d, 0xcc, 0x8c, 0xd9, 0x52, 0x48, 0x6d, 0xbb, 0xd5, 0x63, 0xd6, 0xb6, 0x1a, 0xb8, 0xce, 0x2c,
	0xb7, 0x79, 0x42, 0x83, 0x8f, 0x99, 0x5e, 0x2b, 0xe4, 0x32, 0xc9, 0x6c, 0x4b, 0x8e, 0x7a, 0xed,
	0x22, 0x46, 0x67, 0xc6, 0x55, 0x46, 0xa3, 0xbb, 0x3a, 0x8d, 0x3f, 0x7e, 0x01, 0x51, 0x35, 0xaf,
	0x66, 0x21, 0x6e, 0x71, 0xe3, 0xd7, 0xc4, 0x98, 0xbb, 0x97, 0xaa, 0x6e, 0xb7, 0xc0, 0x1d, 0x5e,
	0xd6, 0xbf, 0xae, 0xc5, 0x6f, 0xa0, 0xbb, 0x3f, 0xaf, 0x27, 0xb8, 0x9f, 0xef, 0x73, 0x3b, 0xe3,
	0x8f, 0x7c, 0xf3, 0x77, 0xef, 0xe0, 0xfe, 0x75, 0x2f, 0xa1, 0xbb, 0x3f, 0x04, 0xf7, 0x92, 0xf2,
	0x6f, 0x0d, 0xa2, 0xea, 0x5d, 0x23, 0x31, 0x44, 0x37, 0x79, 0x99, 0xab, 0x6c, 0x3b, 0x29, 0xdb,
	0x33, 0xf9, 0x6e, 0xb7, 0x8a, 0x6e, 0x85, 0x2f, 0xce, 0x3d, 0x8f, 0x67, 0x76, 0xf1, 0x13, 0xe8,
	0x7a, 0x73, 0xa6, 0xb0, 0x74, 0xef, 0xa5, 0xd9, 0x3f, 0xe7, 0x9b, 0x62, 0xa9, 0xc9, 0x33, 0xe8,
	0x28, 0xcd, 0xf5, 0x4a, 0xcd, 0x12, 0x91, 0xba, 0xd6, 0xf7, 0x18, 0x38, 0xd7, 0x44, 0xa4, 0xf8,
	0xbe, 0x0b, 0xf7, 0x0d, 0x74, 0xf6, 0x7e, 0x05, 0xf7, 0xaa, 0xdb, 0x6b, 0x68, 0x6f, 0x5f, 0xea,
	0x13, 0xc4, 0x8b, 0x43, 0x19, 0x1f, 0x78, 0x19, 0x6f, 0xf9, 0xfc, 0x9d, 0x71, 0xef, 0xdd, 0x74,
	0xdd, 0xb4, 0x6b, 0xf1, 0xfc, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xe5, 0x90, 0x88, 0x3d,
	0x07, 0x00, 0x00,
}
