// Code generated by protoc-gen-go. DO NOT EDIT.
// source: error.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/lyft/protoc-gen-validate/validate"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// one of exception or log is required, enforced on intake
type Error struct {
	Timestamp     *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id            string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TraceId       string               `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TransactionId string               `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ParentId      string               `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	//Context context
	Culprit              string   `protobuf:"bytes,6,opt,name=culprit,proto3" json:"culprit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Error) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Error) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Error) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Error) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Error) GetCulprit() string {
	if m != nil {
		return m.Culprit
	}
	return ""
}

type Error_Transaction struct {
	Sampled              bool     `protobuf:"varint,1,opt,name=sampled,proto3" json:"sampled,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_Transaction) Reset()         { *m = Error_Transaction{} }
func (m *Error_Transaction) String() string { return proto.CompactTextString(m) }
func (*Error_Transaction) ProtoMessage()    {}
func (*Error_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0, 0}
}

func (m *Error_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Transaction.Unmarshal(m, b)
}
func (m *Error_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Transaction.Marshal(b, m, deterministic)
}
func (m *Error_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Transaction.Merge(m, src)
}
func (m *Error_Transaction) XXX_Size() int {
	return xxx_messageInfo_Error_Transaction.Size(m)
}
func (m *Error_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Transaction proto.InternalMessageInfo

func (m *Error_Transaction) GetSampled() bool {
	if m != nil {
		return m.Sampled
	}
	return false
}

func (m *Error_Transaction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// one of message or type is required if exception is provided
type Error_Exception struct {
	// Types that are valid to be assigned to Code:
	//	*Error_Exception_NumberValue
	//	*Error_Exception_StringValue
	Code    isError_Exception_Code `protobuf_oneof:"code"`
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Module  string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	// attributes = 5;
	// stacktrace = 6;
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Handled              bool     `protobuf:"varint,8,opt,name=handled,proto3" json:"handled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_Exception) Reset()         { *m = Error_Exception{} }
func (m *Error_Exception) String() string { return proto.CompactTextString(m) }
func (*Error_Exception) ProtoMessage()    {}
func (*Error_Exception) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0, 1}
}

func (m *Error_Exception) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Exception.Unmarshal(m, b)
}
func (m *Error_Exception) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Exception.Marshal(b, m, deterministic)
}
func (m *Error_Exception) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Exception.Merge(m, src)
}
func (m *Error_Exception) XXX_Size() int {
	return xxx_messageInfo_Error_Exception.Size(m)
}
func (m *Error_Exception) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Exception.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Exception proto.InternalMessageInfo

type isError_Exception_Code interface {
	isError_Exception_Code()
}

type Error_Exception_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,1,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Error_Exception_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Error_Exception_NumberValue) isError_Exception_Code() {}

func (*Error_Exception_StringValue) isError_Exception_Code() {}

func (m *Error_Exception) GetCode() isError_Exception_Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Error_Exception) GetNumberValue() float64 {
	if x, ok := m.GetCode().(*Error_Exception_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (m *Error_Exception) GetStringValue() string {
	if x, ok := m.GetCode().(*Error_Exception_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Error_Exception) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error_Exception) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Error_Exception) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Error_Exception) GetHandled() bool {
	if m != nil {
		return m.Handled
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Error_Exception) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Error_Exception_NumberValue)(nil),
		(*Error_Exception_StringValue)(nil),
	}
}

// message is required if log is provided
type Error_Log struct {
	Level                string   `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	LoggerName           string   `protobuf:"bytes,2,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ParamName            string   `protobuf:"bytes,4,opt,name=param_name,json=paramName,proto3" json:"param_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_Log) Reset()         { *m = Error_Log{} }
func (m *Error_Log) String() string { return proto.CompactTextString(m) }
func (*Error_Log) ProtoMessage()    {}
func (*Error_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0, 2}
}

func (m *Error_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Log.Unmarshal(m, b)
}
func (m *Error_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Log.Marshal(b, m, deterministic)
}
func (m *Error_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Log.Merge(m, src)
}
func (m *Error_Log) XXX_Size() int {
	return xxx_messageInfo_Error_Log.Size(m)
}
func (m *Error_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Log proto.InternalMessageInfo

func (m *Error_Log) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Error_Log) GetLoggerName() string {
	if m != nil {
		return m.LoggerName
	}
	return ""
}

func (m *Error_Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error_Log) GetParamName() string {
	if m != nil {
		return m.ParamName
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "model.Error")
	proto.RegisterType((*Error_Transaction)(nil), "model.Error.Transaction")
	proto.RegisterType((*Error_Exception)(nil), "model.Error.Exception")
	proto.RegisterType((*Error_Log)(nil), "model.Error.Log")
}

func init() { proto.RegisterFile("error.proto", fileDescriptor_0579b252106fcf4a) }

var fileDescriptor_0579b252106fcf4a = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x8b, 0xd4, 0x30,
	0x14, 0xc7, 0xed, 0xcc, 0x74, 0xa6, 0x7d, 0x5d, 0x45, 0x72, 0xb1, 0xf6, 0xa0, 0xc3, 0x2a, 0xb2,
	0x22, 0x4c, 0x45, 0x2f, 0x82, 0xb7, 0x85, 0x05, 0x07, 0xc4, 0x43, 0x58, 0xbc, 0x0e, 0x99, 0xe6,
	0x59, 0x03, 0x49, 0x13, 0xd2, 0x74, 0xd0, 0x9b, 0x5f, 0xc3, 0xcf, 0xe1, 0xcd, 0x93, 0x5f, 0xc5,
	0xa3, 0xdf, 0x42, 0x92, 0xb4, 0xee, 0x3a, 0x2b, 0xde, 0xf2, 0xde, 0xff, 0xf7, 0xfe, 0xbc, 0xff,
	0x23, 0x50, 0xa0, 0xb5, 0xda, 0x6e, 0x8c, 0xd5, 0x4e, 0x93, 0x54, 0x69, 0x8e, 0xb2, 0x7a, 0xd8,
	0x6a, 0xdd, 0x4a, 0xac, 0x43, 0x73, 0x3f, 0x7c, 0xa8, 0x9d, 0x50, 0xd8, 0x3b, 0xa6, 0x4c, 0xe4,
	0xaa, 0x7b, 0x07, 0x26, 0x05, 0x67, 0x0e, 0xeb, 0xe9, 0x11, 0x85, 0xd3, 0x6f, 0x29, 0xa4, 0x17,
	0xde, 0x90, 0xbc, 0x82, 0xfc, 0xcf, 0x54, 0x99, 0xac, 0x93, 0xb3, 0xe2, 0x45, 0xb5, 0x89, 0xbe,
	0x9b, 0xc9, 0x77, 0x73, 0x39, 0x11, 0xf4, 0x0a, 0x26, 0xf7, 0x61, 0x26, 0x78, 0x39, 0x5b, 0x27,
	0x67, 0xf9, 0x79, 0xfe, 0xfd, 0xd7, 0x8f, 0xf9, 0xc2, 0xce, 0xee, 0x26, 0x74, 0x26, 0x38, 0x79,
	0x0c, 0x99, 0xb3, 0xac, 0xc1, 0x9d, 0xe0, 0xe5, 0xe2, 0x18, 0x58, 0x05, 0x69, 0xcb, 0xc9, 0x73,
	0xb8, 0xe3, 0x2c, 0xeb, 0x7a, 0xd6, 0x38, 0xa1, 0x3b, 0xcf, 0xce, 0x8f, 0xd9, 0xdb, 0xd7, 0x80,
	0x2d, 0x27, 0x4f, 0x20, 0x37, 0xcc, 0x62, 0xe7, 0x3c, 0x9c, 0x1e, 0xc3, 0x59, 0xd4, 0xb6, 0x9c,
	0x94, 0xb0, 0x6a, 0x06, 0x69, 0xac, 0x70, 0xe5, 0xd2, 0x53, 0x74, 0x2a, 0xab, 0xd7, 0x50, 0x5c,
	0x5e, 0x59, 0x7a, 0xb0, 0x67, 0xca, 0x48, 0xe4, 0x21, 0x7b, 0x46, 0xa7, 0x92, 0x10, 0x58, 0xb8,
	0xcf, 0x06, 0x63, 0x3e, 0x1a, 0xde, 0xd5, 0xcf, 0x04, 0xf2, 0x8b, 0x4f, 0x0d, 0x9a, 0x30, 0xfb,
	0x08, 0x4e, 0xba, 0x41, 0xed, 0xd1, 0xee, 0x0e, 0x4c, 0x0e, 0x18, 0x0c, 0x92, 0x37, 0xb7, 0x68,
	0x11, 0xbb, 0xef, 0x7d, 0x93, 0xd4, 0x70, 0xd2, 0x3b, 0x2b, 0xba, 0x76, 0x84, 0xe2, 0xb9, 0xc0,
	0x2f, 0x9d, 0xda, 0x79, 0xf9, 0x25, 0xf3, 0x03, 0x91, 0x88, 0x03, 0x25, 0xac, 0x14, 0xf6, 0x3d,
	0x6b, 0x31, 0x5e, 0x83, 0x4e, 0x25, 0x39, 0x85, 0xa5, 0xd2, 0x7c, 0x90, 0x38, 0x9e, 0xf4, 0x9a,
	0x09, 0x1d, 0x15, 0xf2, 0x60, 0xdc, 0x7a, 0x75, 0x83, 0x08, 0x7d, 0xef, 0xfe, 0x91, 0x75, 0xdc,
	0xe7, 0xcd, 0x62, 0xde, 0xb1, 0x3c, 0x5f, 0xc2, 0xa2, 0xd1, 0x1c, 0xab, 0xaf, 0x09, 0xcc, 0xdf,
	0xea, 0x96, 0xac, 0x21, 0x95, 0x78, 0x40, 0x19, 0x62, 0xfd, 0x6d, 0x15, 0x05, 0xf2, 0x0c, 0x0a,
	0xa9, 0xdb, 0x16, 0xed, 0xae, 0x63, 0xea, 0x1f, 0xc9, 0x28, 0x44, 0xf9, 0x1d, 0x53, 0xff, 0x8b,
	0xf5, 0x14, 0xc0, 0x30, 0xcb, 0x54, 0x74, 0xb9, 0x19, 0x2d, 0x0f, 0xaa, 0x37, 0xd9, 0x2f, 0xc3,
	0x87, 0x7c, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xae, 0x27, 0x83, 0x0c, 0x03, 0x00, 0x00,
}
