// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package model

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

type Metadata_Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata_Service) Reset()         { *m = Metadata_Service{} }
func (m *Metadata_Service) String() string { return proto.CompactTextString(m) }
func (*Metadata_Service) ProtoMessage()    {}
func (*Metadata_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0, 0}
}

func (m *Metadata_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata_Service.Unmarshal(m, b)
}
func (m *Metadata_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata_Service.Marshal(b, m, deterministic)
}
func (m *Metadata_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata_Service.Merge(m, src)
}
func (m *Metadata_Service) XXX_Size() int {
	return xxx_messageInfo_Metadata_Service.Size(m)
}
func (m *Metadata_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata_Service proto.InternalMessageInfo

func (m *Metadata_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EventsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Metadata)(nil), "model.Metadata")
	proto.RegisterType((*Metadata_Service)(nil), "model.Metadata.Service")
	proto.RegisterType((*EventsResponse)(nil), "model.EventsResponse")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49,
	0xcd, 0x51, 0xd2, 0xe4, 0xe2, 0xf0, 0x85, 0x4a, 0x48, 0xc9, 0x72, 0xb1, 0x07, 0xa7, 0x16, 0x95,
	0x65, 0x26, 0xa7, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x4a, 0x02, 0x5c, 0x7c, 0xae, 0x65, 0xa9, 0x79, 0x25, 0xc5, 0x41, 0xa9,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x46, 0xb6, 0x5c, 0xcc, 0x8e, 0x05, 0xb9, 0x42, 0x66, 0x5c,
	0x5c, 0xc1, 0xa9, 0x79, 0x29, 0x10, 0x49, 0x21, 0x7e, 0x3d, 0xb0, 0xc9, 0x7a, 0x70, 0x63, 0x45,
	0xa1, 0x02, 0xa8, 0x9a, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x2e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xfc, 0x3e, 0x3d, 0x5e, 0x9b, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApmClient is the client API for Apm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApmClient interface {
	SendEvents(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*EventsResponse, error)
}

type apmClient struct {
	cc *grpc.ClientConn
}

func NewApmClient(cc *grpc.ClientConn) ApmClient {
	return &apmClient{cc}
}

func (c *apmClient) SendEvents(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*EventsResponse, error) {
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, "/model.Apm/SendEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApmServer is the server API for Apm service.
type ApmServer interface {
	SendEvents(context.Context, *Metadata) (*EventsResponse, error)
}

func RegisterApmServer(s *grpc.Server, srv ApmServer) {
	s.RegisterService(&_Apm_serviceDesc, srv)
}

func _Apm_SendEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApmServer).SendEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Apm/SendEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApmServer).SendEvents(ctx, req.(*Metadata))
	}
	return interceptor(ctx, in, info, handler)
}

var _Apm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Apm",
	HandlerType: (*ApmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvents",
			Handler:    _Apm_SendEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata.proto",
}
