// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Process              *Process `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	System               *System  `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	User                 *User    `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Metadata) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Metadata) GetSystem() *System {
	if m != nil {
		return m.System
	}
	return nil
}

func (m *Metadata) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "model.Metadata")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49,
	0xcd, 0x91, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x85, 0x88, 0x4a, 0xf1, 0x16, 0x14,
	0xe5, 0x27, 0xa7, 0x16, 0x17, 0x43, 0xb9, 0x3c, 0xc5, 0x95, 0xc5, 0x25, 0xa9, 0xb9, 0x50, 0x1e,
	0x57, 0x69, 0x71, 0x6a, 0x11, 0x84, 0xad, 0xb4, 0x8c, 0x91, 0x8b, 0xc3, 0x17, 0x6a, 0xa2, 0x90,
	0x06, 0x17, 0x3b, 0xd4, 0x18, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x3e, 0x3d, 0xb0, 0xe9,
	0x7a, 0xc1, 0x10, 0xd1, 0x20, 0x98, 0x34, 0x48, 0x25, 0xd4, 0x06, 0x09, 0x26, 0x14, 0x95, 0x01,
	0x10, 0xd1, 0x20, 0x98, 0xb4, 0x90, 0x2a, 0x17, 0x1b, 0xc4, 0x72, 0x09, 0x66, 0xb0, 0x42, 0x5e,
	0x98, 0x91, 0x60, 0xc1, 0x20, 0xa8, 0xa4, 0x90, 0x3c, 0x17, 0x0b, 0xc8, 0x55, 0x12, 0x2c, 0x60,
	0x45, 0xdc, 0x50, 0x45, 0xa1, 0xc5, 0xa9, 0x45, 0x41, 0x60, 0x89, 0x24, 0x36, 0xb0, 0x7b, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xc1, 0x45, 0xa0, 0x00, 0x01, 0x00, 0x00,
}
