// Code generated by protoc-gen-go. DO NOT EDIT.
// source: process.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Process struct {
	Pid                  int32              `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid                 int32              `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Title                string             `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Argv                 *_struct.ListValue `protobuf:"bytes,4,opt,name=argv,proto3" json:"argv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c4d0e8c0aaf5c3, []int{0}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Process) GetPpid() int32 {
	if m != nil {
		return m.Ppid
	}
	return 0
}

func (m *Process) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Process) GetArgv() *_struct.ListValue {
	if m != nil {
		return m.Argv
	}
	return nil
}

func init() {
	proto.RegisterType((*Process)(nil), "model.Process")
}

func init() { proto.RegisterFile("process.proto", fileDescriptor_54c4d0e8c0aaf5c3) }

var fileDescriptor_54c4d0e8c0aaf5c3 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0x4e, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd,
	0x91, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x26, 0x95, 0xa6, 0xe9, 0x17,
	0x97, 0x14, 0x95, 0x26, 0x97, 0x40, 0x14, 0x29, 0x95, 0x72, 0xb1, 0x07, 0x40, 0x74, 0x09, 0x09,
	0x70, 0x31, 0x17, 0x64, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0x98, 0x42, 0x42,
	0x5c, 0x2c, 0x05, 0x20, 0x21, 0x26, 0xb0, 0x10, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x59,
	0x92, 0x93, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0xe9, 0x71, 0xb1, 0x24,
	0x16, 0xa5, 0x97, 0x49, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0x41, 0xec, 0xd4, 0x83,
	0xd9, 0xa9, 0xe7, 0x93, 0x59, 0x5c, 0x12, 0x96, 0x98, 0x53, 0x9a, 0x1a, 0x04, 0x56, 0x97, 0xc4,
	0x06, 0x96, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x56, 0xff, 0x09, 0xb3, 0x00, 0x00,
	0x00,
}
