// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Agent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Framework struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Framework) Reset()         { *m = Framework{} }
func (m *Framework) String() string { return proto.CompactTextString(m) }
func (*Framework) ProtoMessage()    {}
func (*Framework) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Framework) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Framework.Unmarshal(m, b)
}
func (m *Framework) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Framework.Marshal(b, m, deterministic)
}
func (m *Framework) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Framework.Merge(m, src)
}
func (m *Framework) XXX_Size() int {
	return xxx_messageInfo_Framework.Size(m)
}
func (m *Framework) XXX_DiscardUnknown() {
	xxx_messageInfo_Framework.DiscardUnknown(m)
}

var xxx_messageInfo_Framework proto.InternalMessageInfo

func (m *Framework) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Framework) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Language struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Language) Reset()         { *m = Language{} }
func (m *Language) String() string { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()    {}
func (*Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Language.Unmarshal(m, b)
}
func (m *Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Language.Marshal(b, m, deterministic)
}
func (m *Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Language.Merge(m, src)
}
func (m *Language) XXX_Size() int {
	return xxx_messageInfo_Language.Size(m)
}
func (m *Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Language proto.InternalMessageInfo

func (m *Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Language) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Runtime struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Runtime) Reset()         { *m = Runtime{} }
func (m *Runtime) String() string { return proto.CompactTextString(m) }
func (*Runtime) ProtoMessage()    {}
func (*Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Runtime.Unmarshal(m, b)
}
func (m *Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Runtime.Marshal(b, m, deterministic)
}
func (m *Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Runtime.Merge(m, src)
}
func (m *Runtime) XXX_Size() int {
	return xxx_messageInfo_Runtime.Size(m)
}
func (m *Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_Runtime proto.InternalMessageInfo

func (m *Runtime) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Runtime) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Environment          string     `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Version              string     `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Agent                *Agent     `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Framework            *Framework `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	Language             *Language  `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Runtime              *Runtime   `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *Service) GetFramework() *Framework {
	if m != nil {
		return m.Framework
	}
	return nil
}

func (m *Service) GetLanguage() *Language {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *Service) GetRuntime() *Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

func init() {
	proto.RegisterType((*Agent)(nil), "model.Agent")
	proto.RegisterType((*Framework)(nil), "model.Framework")
	proto.RegisterType((*Language)(nil), "model.Language")
	proto.RegisterType((*Runtime)(nil), "model.Runtime")
	proto.RegisterType((*Service)(nil), "model.Service")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0xd2, 0xd4, 0xcd, 0x95, 0x7f, 0xba, 0xc9, 0x63, 0x94, 0x29, 0x12, 0x52, 0x06,
	0x10, 0x02, 0x46, 0x16, 0x26, 0x26, 0xf3, 0x04, 0x06, 0x8e, 0x28, 0xa2, 0x3e, 0x23, 0x37, 0x0d,
	0x2f, 0xc0, 0x83, 0x23, 0x2e, 0x76, 0x09, 0x12, 0x4b, 0x36, 0xfb, 0xee, 0xf7, 0x7d, 0x92, 0x7f,
	0x86, 0x93, 0x1d, 0x85, 0xa1, 0x7b, 0xa1, 0xe6, 0x23, 0xf8, 0xde, 0x63, 0xee, 0xfc, 0x2b, 0x6d,
	0xab, 0x6b, 0xc8, 0xef, 0x5b, 0xe2, 0x1e, 0x11, 0x96, 0x6c, 0x1d, 0xe9, 0xac, 0xcc, 0xea, 0xc2,
	0xc8, 0x19, 0x35, 0xa8, 0x81, 0xc2, 0xae, 0xf3, 0xac, 0x17, 0x32, 0x4e, 0xd7, 0xea, 0x0e, 0x8a,
	0x87, 0x60, 0x1d, 0x7d, 0xfa, 0xf0, 0x3e, 0x33, 0x7a, 0x0b, 0xeb, 0x47, 0xcb, 0xed, 0xde, 0xb6,
	0x34, 0x33, 0x79, 0x03, 0xca, 0xec, 0xb9, 0xef, 0xdc, 0xdc, 0xe0, 0xd7, 0x02, 0xd4, 0xd3, 0xf8,
	0xfa, 0x7f, 0x93, 0x25, 0x6c, 0x88, 0x87, 0x2e, 0x78, 0x76, 0xc4, 0x7d, 0x4c, 0x4f, 0x47, 0xd3,
	0xee, 0xa3, 0x3f, 0xdd, 0x58, 0x41, 0x6e, 0x7f, 0x04, 0xea, 0x65, 0x99, 0xd5, 0x9b, 0xcb, 0xe3,
	0x46, 0xbc, 0x36, 0x22, 0xd5, 0x8c, 0x2b, 0x6c, 0xa0, 0x78, 0x4b, 0xb6, 0x74, 0x2e, 0xdc, 0x79,
	0xe4, 0x0e, 0x16, 0xcd, 0x2f, 0x82, 0x17, 0xb0, 0xde, 0x46, 0x45, 0x7a, 0x25, 0xf8, 0x59, 0xc4,
	0x93, 0x39, 0x73, 0x00, 0xb0, 0x06, 0x15, 0x46, 0x2b, 0x5a, 0x09, 0x7b, 0x1a, 0xd9, 0xe8, 0xca,
	0xa4, 0xf5, 0xf3, 0x4a, 0x7e, 0xfe, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x09, 0x5c, 0xe0, 0x84,
	0x0a, 0x02, 0x00, 0x00,
}
