// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/lyft/protoc-gen-validate/validate"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Environment          string             `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Version              string             `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Agent                *Service_Agent     `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Framework            *Service_Framework `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	Language             *Service_Language  `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Runtime              *Service_Runtime   `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetAgent() *Service_Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *Service) GetFramework() *Service_Framework {
	if m != nil {
		return m.Framework
	}
	return nil
}

func (m *Service) GetLanguage() *Service_Language {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *Service) GetRuntime() *Service_Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

type Service_Agent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Agent) Reset()         { *m = Service_Agent{} }
func (m *Service_Agent) String() string { return proto.CompactTextString(m) }
func (*Service_Agent) ProtoMessage()    {}
func (*Service_Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 0}
}

func (m *Service_Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Agent.Unmarshal(m, b)
}
func (m *Service_Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Agent.Marshal(b, m, deterministic)
}
func (m *Service_Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Agent.Merge(m, src)
}
func (m *Service_Agent) XXX_Size() int {
	return xxx_messageInfo_Service_Agent.Size(m)
}
func (m *Service_Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Agent proto.InternalMessageInfo

func (m *Service_Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Agent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service_Framework struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Framework) Reset()         { *m = Service_Framework{} }
func (m *Service_Framework) String() string { return proto.CompactTextString(m) }
func (*Service_Framework) ProtoMessage()    {}
func (*Service_Framework) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 1}
}

func (m *Service_Framework) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Framework.Unmarshal(m, b)
}
func (m *Service_Framework) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Framework.Marshal(b, m, deterministic)
}
func (m *Service_Framework) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Framework.Merge(m, src)
}
func (m *Service_Framework) XXX_Size() int {
	return xxx_messageInfo_Service_Framework.Size(m)
}
func (m *Service_Framework) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Framework.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Framework proto.InternalMessageInfo

func (m *Service_Framework) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Framework) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service_Language struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Language) Reset()         { *m = Service_Language{} }
func (m *Service_Language) String() string { return proto.CompactTextString(m) }
func (*Service_Language) ProtoMessage()    {}
func (*Service_Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 2}
}

func (m *Service_Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Language.Unmarshal(m, b)
}
func (m *Service_Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Language.Marshal(b, m, deterministic)
}
func (m *Service_Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Language.Merge(m, src)
}
func (m *Service_Language) XXX_Size() int {
	return xxx_messageInfo_Service_Language.Size(m)
}
func (m *Service_Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Language proto.InternalMessageInfo

func (m *Service_Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Language) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service_Runtime struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Runtime) Reset()         { *m = Service_Runtime{} }
func (m *Service_Runtime) String() string { return proto.CompactTextString(m) }
func (*Service_Runtime) ProtoMessage()    {}
func (*Service_Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 3}
}

func (m *Service_Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Runtime.Unmarshal(m, b)
}
func (m *Service_Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Runtime.Marshal(b, m, deterministic)
}
func (m *Service_Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Runtime.Merge(m, src)
}
func (m *Service_Runtime) XXX_Size() int {
	return xxx_messageInfo_Service_Runtime.Size(m)
}
func (m *Service_Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Runtime proto.InternalMessageInfo

func (m *Service_Runtime) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Runtime) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Service)(nil), "model.Service")
	proto.RegisterType((*Service_Agent)(nil), "model.Service.Agent")
	proto.RegisterType((*Service_Framework)(nil), "model.Service.Framework")
	proto.RegisterType((*Service_Language)(nil), "model.Service.Language")
	proto.RegisterType((*Service_Runtime)(nil), "model.Service.Runtime")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd,
	0x91, 0x12, 0x2f, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0x49, 0xd5, 0x87, 0x31, 0x20, 0xf2, 0x4a,
	0xbd, 0xac, 0x5c, 0xec, 0xc1, 0x10, 0x1d, 0x42, 0x72, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x4e, 0x5c, 0xbb, 0x5e, 0x1e, 0x60, 0x66, 0x2d, 0x62, 0x96, 0x68,
	0xe0, 0x08, 0x02, 0x8b, 0x0b, 0xe9, 0x70, 0x71, 0xa7, 0xe6, 0x95, 0x65, 0x16, 0xe5, 0xe7, 0xe5,
	0xa6, 0xe6, 0x95, 0x48, 0x30, 0x61, 0x28, 0x43, 0x96, 0x16, 0x52, 0xe1, 0x62, 0x2f, 0x4b, 0x2d,
	0x2a, 0xce, 0xcc, 0xcf, 0x93, 0x60, 0xc6, 0x50, 0x09, 0x93, 0x12, 0xd2, 0xe2, 0x62, 0x4d, 0x4c,
	0x07, 0x99, 0xc6, 0xa2, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0x76, 0xaf, 0x1e, 0xd4, 0x49,
	0x7a, 0x8e, 0x20, 0xb9, 0x20, 0x88, 0x12, 0x21, 0x33, 0x2e, 0xce, 0xb4, 0xa2, 0xc4, 0xdc, 0xd4,
	0xf2, 0xfc, 0xa2, 0x6c, 0x09, 0x56, 0xb0, 0x7a, 0x09, 0x34, 0xf5, 0x6e, 0x30, 0xf9, 0x20, 0x84,
	0x52, 0x21, 0x63, 0x2e, 0x8e, 0x9c, 0xc4, 0xbc, 0xf4, 0xd2, 0xc4, 0xf4, 0x54, 0x09, 0x36, 0xb0,
	0x36, 0x71, 0x34, 0x6d, 0x3e, 0x50, 0xe9, 0x20, 0xb8, 0x42, 0x21, 0x03, 0x2e, 0xf6, 0xa2, 0xd2,
	0xbc, 0x92, 0xcc, 0xdc, 0x54, 0x09, 0x76, 0xb0, 0x1e, 0x31, 0x34, 0x3d, 0x41, 0x10, 0xd9, 0x20,
	0x98, 0x32, 0x29, 0x5f, 0x2e, 0x56, 0xb0, 0x73, 0x09, 0x86, 0x23, 0x52, 0xc8, 0x30, 0xe1, 0x0c,
	0x19, 0xa9, 0x40, 0x2e, 0x4e, 0xb8, 0x6f, 0xa8, 0x64, 0x64, 0x00, 0x17, 0x07, 0xcc, 0xa7, 0x54,
	0x32, 0xd1, 0x9f, 0x8b, 0x1d, 0x1a, 0x0e, 0xd4, 0x31, 0x30, 0x89, 0x0d, 0x9c, 0x2c, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0xce, 0xb6, 0x7c, 0xc7, 0x02, 0x00, 0x00,
}
