// Code generated by protoc-gen-go. DO NOT EDIT.
// source: span.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/lyft/protoc-gen-validate/validate"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// one of timestamp or start are required, enforced on intake
type Span struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId        string               `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TraceId              string               `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentId             string               `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Start                uint64               `protobuf:"varint,6,opt,name=start,proto3" json:"start,omitempty"`
	Subtype              string               `protobuf:"bytes,7,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Action               string               `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	Context              *Span_Context        `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,10,opt,name=duration,proto3" json:"duration,omitempty"`
	Name                 string               `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Stacktrace           []*StacktraceFrame2  `protobuf:"bytes,12,rep,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	Type                 string               `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	Sync                 bool                 `protobuf:"varint,14,opt,name=sync,proto3" json:"sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5f2b88b579999f, []int{0}
}

func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (m *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(m, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Span) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Span) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Span) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Span) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Span) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Span) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

func (m *Span) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Span) GetContext() *Span_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Span) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Span) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span) GetStacktrace() []*StacktraceFrame2 {
	if m != nil {
		return m.Stacktrace
	}
	return nil
}

func (m *Span) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Span) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

type Span_Context struct {
	Db                   *Span_Context_Db      `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Http                 *Span_Context_Http    `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Tags                 map[string]*TagValue  `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Service              *Span_Context_Service `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Span_Context) Reset()         { *m = Span_Context{} }
func (m *Span_Context) String() string { return proto.CompactTextString(m) }
func (*Span_Context) ProtoMessage()    {}
func (*Span_Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5f2b88b579999f, []int{0, 0}
}

func (m *Span_Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span_Context.Unmarshal(m, b)
}
func (m *Span_Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span_Context.Marshal(b, m, deterministic)
}
func (m *Span_Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span_Context.Merge(m, src)
}
func (m *Span_Context) XXX_Size() int {
	return xxx_messageInfo_Span_Context.Size(m)
}
func (m *Span_Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Span_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Span_Context proto.InternalMessageInfo

func (m *Span_Context) GetDb() *Span_Context_Db {
	if m != nil {
		return m.Db
	}
	return nil
}

func (m *Span_Context) GetHttp() *Span_Context_Http {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *Span_Context) GetTags() map[string]*TagValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Span_Context) GetService() *Span_Context_Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type Span_Context_Db struct {
	Instance             string   `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Statement            string   `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Span_Context_Db) Reset()         { *m = Span_Context_Db{} }
func (m *Span_Context_Db) String() string { return proto.CompactTextString(m) }
func (*Span_Context_Db) ProtoMessage()    {}
func (*Span_Context_Db) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5f2b88b579999f, []int{0, 0, 0}
}

func (m *Span_Context_Db) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span_Context_Db.Unmarshal(m, b)
}
func (m *Span_Context_Db) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span_Context_Db.Marshal(b, m, deterministic)
}
func (m *Span_Context_Db) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span_Context_Db.Merge(m, src)
}
func (m *Span_Context_Db) XXX_Size() int {
	return xxx_messageInfo_Span_Context_Db.Size(m)
}
func (m *Span_Context_Db) XXX_DiscardUnknown() {
	xxx_messageInfo_Span_Context_Db.DiscardUnknown(m)
}

var xxx_messageInfo_Span_Context_Db proto.InternalMessageInfo

func (m *Span_Context_Db) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *Span_Context_Db) GetStatement() string {
	if m != nil {
		return m.Statement
	}
	return ""
}

func (m *Span_Context_Db) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Span_Context_Db) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type Span_Context_Http struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	StatusCode           uint32   `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Span_Context_Http) Reset()         { *m = Span_Context_Http{} }
func (m *Span_Context_Http) String() string { return proto.CompactTextString(m) }
func (*Span_Context_Http) ProtoMessage()    {}
func (*Span_Context_Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5f2b88b579999f, []int{0, 0, 1}
}

func (m *Span_Context_Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span_Context_Http.Unmarshal(m, b)
}
func (m *Span_Context_Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span_Context_Http.Marshal(b, m, deterministic)
}
func (m *Span_Context_Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span_Context_Http.Merge(m, src)
}
func (m *Span_Context_Http) XXX_Size() int {
	return xxx_messageInfo_Span_Context_Http.Size(m)
}
func (m *Span_Context_Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Span_Context_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Span_Context_Http proto.InternalMessageInfo

func (m *Span_Context_Http) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Span_Context_Http) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Span_Context_Http) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Span_Context_Service struct {
	Agent                *Span_Context_Service_Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Name                 string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Span_Context_Service) Reset()         { *m = Span_Context_Service{} }
func (m *Span_Context_Service) String() string { return proto.CompactTextString(m) }
func (*Span_Context_Service) ProtoMessage()    {}
func (*Span_Context_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5f2b88b579999f, []int{0, 0, 2}
}

func (m *Span_Context_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span_Context_Service.Unmarshal(m, b)
}
func (m *Span_Context_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span_Context_Service.Marshal(b, m, deterministic)
}
func (m *Span_Context_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span_Context_Service.Merge(m, src)
}
func (m *Span_Context_Service) XXX_Size() int {
	return xxx_messageInfo_Span_Context_Service.Size(m)
}
func (m *Span_Context_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Span_Context_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Span_Context_Service proto.InternalMessageInfo

func (m *Span_Context_Service) GetAgent() *Span_Context_Service_Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *Span_Context_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Span_Context_Service_Agent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Span_Context_Service_Agent) Reset()         { *m = Span_Context_Service_Agent{} }
func (m *Span_Context_Service_Agent) String() string { return proto.CompactTextString(m) }
func (*Span_Context_Service_Agent) ProtoMessage()    {}
func (*Span_Context_Service_Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5f2b88b579999f, []int{0, 0, 2, 0}
}

func (m *Span_Context_Service_Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span_Context_Service_Agent.Unmarshal(m, b)
}
func (m *Span_Context_Service_Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span_Context_Service_Agent.Marshal(b, m, deterministic)
}
func (m *Span_Context_Service_Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span_Context_Service_Agent.Merge(m, src)
}
func (m *Span_Context_Service_Agent) XXX_Size() int {
	return xxx_messageInfo_Span_Context_Service_Agent.Size(m)
}
func (m *Span_Context_Service_Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Span_Context_Service_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Span_Context_Service_Agent proto.InternalMessageInfo

func (m *Span_Context_Service_Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span_Context_Service_Agent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Span)(nil), "model.Span")
	proto.RegisterType((*Span_Context)(nil), "model.Span.Context")
	proto.RegisterMapType((map[string]*TagValue)(nil), "model.Span.Context.TagsEntry")
	proto.RegisterType((*Span_Context_Db)(nil), "model.Span.Context.Db")
	proto.RegisterType((*Span_Context_Http)(nil), "model.Span.Context.Http")
	proto.RegisterType((*Span_Context_Service)(nil), "model.Span.Context.Service")
	proto.RegisterType((*Span_Context_Service_Agent)(nil), "model.Span.Context.Service.Agent")
}

func init() { proto.RegisterFile("span.proto", fileDescriptor_fc5f2b88b579999f) }

var fileDescriptor_fc5f2b88b579999f = []byte{
	// 671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4b, 0x6f, 0xd3, 0x4a,
	0x18, 0x86, 0x65, 0xc7, 0xae, 0xed, 0x2f, 0xa7, 0x3d, 0xd5, 0x9c, 0xa3, 0x76, 0xea, 0x73, 0xda,
	0x06, 0x54, 0xaa, 0x2c, 0xc0, 0x85, 0x20, 0xd4, 0x8a, 0x5d, 0x2f, 0xa0, 0x76, 0xc1, 0x82, 0x69,
	0xc5, 0xb6, 0x9a, 0xd8, 0xd3, 0xd4, 0x6a, 0x7c, 0xd1, 0xcc, 0x38, 0x22, 0x3b, 0xc4, 0x7f, 0x61,
	0xc3, 0x8e, 0x2d, 0x2b, 0xfe, 0x0e, 0xff, 0x02, 0xcd, 0xc5, 0x49, 0x49, 0x23, 0x76, 0x33, 0xf3,
	0x3d, 0x73, 0x79, 0xdf, 0xef, 0x1d, 0x00, 0x51, 0xd3, 0x32, 0xa9, 0x79, 0x25, 0x2b, 0xe4, 0x17,
	0x55, 0xc6, 0xc6, 0xf1, 0xce, 0xa8, 0xaa, 0x46, 0x63, 0x76, 0xa0, 0x17, 0x87, 0xcd, 0xcd, 0x41,
	0xd6, 0x70, 0x2a, 0xf3, 0xca, 0x62, 0xf1, 0xee, 0x62, 0x5d, 0xe6, 0x05, 0x13, 0x92, 0x16, 0xb5,
	0x05, 0x36, 0x27, 0x74, 0x9c, 0x67, 0x54, 0xb2, 0x83, 0x76, 0x60, 0x0b, 0xeb, 0x42, 0xd2, 0xf4,
	0x4e, 0x72, 0x9a, 0xb6, 0x2b, 0x20, 0xe9, 0x48, 0x98, 0xf1, 0xe3, 0x2f, 0x11, 0x78, 0x97, 0x35,
	0x2d, 0xd1, 0x11, 0x44, 0xb3, 0x23, 0xb1, 0xd3, 0x73, 0xfa, 0xdd, 0x41, 0x9c, 0x98, 0x4b, 0x93,
	0xf6, 0xd2, 0xe4, 0xaa, 0x25, 0xc8, 0x1c, 0x46, 0x5b, 0xe0, 0xe6, 0x19, 0x76, 0x7b, 0x4e, 0x3f,
	0x3a, 0x89, 0xbe, 0xff, 0xfc, 0xd1, 0xf1, 0xb8, 0xbb, 0xee, 0x10, 0x37, 0xcf, 0xd0, 0x73, 0x58,
	0x93, 0x9c, 0x96, 0x82, 0xa6, 0x4a, 0xca, 0x75, 0x9e, 0xe1, 0xce, 0x22, 0xb6, 0x7a, 0x0f, 0xb8,
	0xc8, 0xd0, 0x1e, 0x84, 0xfa, 0xa9, 0x8a, 0xf5, 0x16, 0xd9, 0x40, 0x97, 0x2e, 0x32, 0xb4, 0x0f,
	0x51, 0x4d, 0x39, 0x2b, 0xa5, 0xc2, 0xfc, 0x45, 0x2c, 0x34, 0xb5, 0x8b, 0x0c, 0xfd, 0x0b, 0xbe,
	0x90, 0x94, 0x4b, 0xbc, 0xd2, 0x73, 0xfa, 0x1e, 0x31, 0x13, 0x84, 0x21, 0x10, 0xcd, 0x50, 0x4e,
	0x6b, 0x86, 0x03, 0xb5, 0x97, 0xb4, 0x53, 0xb4, 0x01, 0x2b, 0xe6, 0x25, 0x38, 0xd4, 0x05, 0x3b,
	0x43, 0xcf, 0x20, 0x48, 0xab, 0x52, 0xb2, 0x8f, 0x12, 0x47, 0xda, 0x9a, 0x7f, 0x12, 0xdd, 0xb6,
	0x44, 0x59, 0x97, 0x9c, 0x9a, 0x12, 0x69, 0x19, 0x74, 0x0c, 0x61, 0xdb, 0x3e, 0x0c, 0x9a, 0xdf,
	0x7a, 0x60, 0xe5, 0x99, 0x05, 0x4e, 0x40, 0x3d, 0xdc, 0xff, 0xea, 0xb8, 0xa1, 0x43, 0x66, 0xdb,
	0xd0, 0x36, 0x78, 0x25, 0x2d, 0x18, 0xee, 0x2e, 0x8a, 0xd3, 0xcb, 0xe8, 0x10, 0x60, 0xde, 0x56,
	0xfc, 0x57, 0xaf, 0xd3, 0xef, 0x0e, 0x36, 0xdb, 0x37, 0xcd, 0x0a, 0x6f, 0x39, 0x2d, 0xd8, 0x80,
	0xdc, 0x43, 0xd5, 0xb9, 0x5a, 0xf8, 0xea, 0x83, 0x73, 0xb5, 0x01, 0x08, 0x3c, 0x31, 0x2d, 0x53,
	0xbc, 0xd6, 0x73, 0xfa, 0x21, 0xd1, 0xe3, 0xf8, 0xb3, 0x0f, 0x81, 0x95, 0x88, 0xf6, 0xc1, 0xcd,
	0x86, 0x36, 0x1e, 0x1b, 0x4b, 0x3c, 0x48, 0xce, 0x86, 0xc4, 0xcd, 0x86, 0xe8, 0x29, 0x78, 0xb7,
	0x52, 0xd6, 0x3a, 0x15, 0xdd, 0x01, 0x5e, 0x46, 0x9e, 0x4b, 0x59, 0x13, 0x4d, 0xa1, 0x17, 0xe0,
	0xa9, 0x48, 0xe2, 0x8e, 0xd6, 0xb1, 0xbd, 0x8c, 0xbe, 0xa2, 0x23, 0xf1, 0xa6, 0x94, 0x7c, 0x4a,
	0x34, 0x8a, 0x5e, 0x41, 0x20, 0x18, 0x9f, 0xe4, 0x29, 0xd3, 0x31, 0xe9, 0x0e, 0xfe, 0x5b, 0xb6,
	0xeb, 0xd2, 0x20, 0xa4, 0x65, 0xe3, 0x1b, 0x70, 0xcf, 0x86, 0x28, 0x86, 0x30, 0x2f, 0x85, 0xa4,
	0x65, 0xca, 0xb4, 0x96, 0x88, 0xcc, 0xe6, 0xe8, 0x7f, 0x88, 0x84, 0xa4, 0x92, 0x15, 0xac, 0x94,
	0x26, 0xd4, 0x64, 0xbe, 0xa0, 0xfc, 0xd1, 0xf6, 0xe9, 0x18, 0xcf, 0x3d, 0x6b, 0x04, 0xe3, 0x26,
	0xae, 0x44, 0x8f, 0xe3, 0xf7, 0xe0, 0x29, 0x7d, 0x68, 0x1d, 0x3a, 0x0d, 0x1f, 0xdb, 0x4b, 0xd4,
	0x10, 0xed, 0x42, 0x57, 0x1d, 0xd7, 0x88, 0xeb, 0xb4, 0xca, 0x98, 0xbe, 0x61, 0x55, 0x77, 0x48,
	0x36, 0xe2, 0xb4, 0xca, 0x74, 0x06, 0x0b, 0x26, 0x6f, 0x2b, 0xfb, 0x57, 0x88, 0x9d, 0xc5, 0xdf,
	0x1c, 0x08, 0xac, 0x1e, 0x74, 0x08, 0x3e, 0x1d, 0xa9, 0x07, 0x9a, 0x4e, 0x3c, 0xfa, 0x83, 0xf6,
	0xe4, 0x58, 0x81, 0xc4, 0xf0, 0x68, 0xc7, 0xc6, 0xca, 0xfc, 0x56, 0x13, 0x3d, 0xde, 0xc1, 0x9f,
	0x42, 0x93, 0xab, 0xf8, 0x1d, 0xf8, 0xc7, 0xbf, 0x81, 0xce, 0x72, 0x10, 0xed, 0x41, 0x30, 0x61,
	0x5c, 0xa8, 0x84, 0x3f, 0x3c, 0xab, 0x2d, 0xc5, 0xe7, 0x10, 0xcd, 0x1a, 0xa7, 0xbc, 0xb8, 0x63,
	0xd3, 0xd6, 0x8b, 0x3b, 0x36, 0x45, 0x4f, 0xc0, 0x9f, 0xd0, 0x71, 0xc3, 0x6c, 0x4c, 0xfe, 0xb6,
	0x32, 0xae, 0xe8, 0xe8, 0x83, 0x5a, 0x26, 0xa6, 0xfa, 0xda, 0x3d, 0x72, 0x86, 0x2b, 0xfa, 0xe3,
	0xbc, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x5f, 0x7b, 0x3f, 0x3b, 0x05, 0x00, 0x00,
}
