// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stacktrace.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on StacktraceFrame2 with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *StacktraceFrame2) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for AbsPath

	// no validation rules for Colno

	// no validation rules for ContextLine

	if utf8.RuneCountInString(m.GetFilename()) < 1 {
		return StacktraceFrame2ValidationError{
			field:  "Filename",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for Function

	// no validation rules for LibraryFrame

	// no validation rules for Lineno

	// no validation rules for Module

	if v, ok := interface{}(m.GetPostContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StacktraceFrame2ValidationError{
				field:  "PostContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetPreContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StacktraceFrame2ValidationError{
				field:  "PreContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Vars

	return nil
}

// StacktraceFrame2ValidationError is the validation error returned by
// StacktraceFrame2.Validate if the designated constraints aren't met.
type StacktraceFrame2ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StacktraceFrame2ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StacktraceFrame2ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StacktraceFrame2ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StacktraceFrame2ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StacktraceFrame2ValidationError) ErrorName() string { return "StacktraceFrame2ValidationError" }

// Error satisfies the builtin error interface
func (e StacktraceFrame2ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStacktraceFrame2.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StacktraceFrame2ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StacktraceFrame2ValidationError{}
