// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Kubernetes struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kubernetes) Reset()         { *m = Kubernetes{} }
func (m *Kubernetes) String() string { return proto.CompactTextString(m) }
func (*Kubernetes) ProtoMessage()    {}
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{1}
}

func (m *Kubernetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kubernetes.Unmarshal(m, b)
}
func (m *Kubernetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kubernetes.Marshal(b, m, deterministic)
}
func (m *Kubernetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kubernetes.Merge(m, src)
}
func (m *Kubernetes) XXX_Size() int {
	return xxx_messageInfo_Kubernetes.Size(m)
}
func (m *Kubernetes) XXX_DiscardUnknown() {
	xxx_messageInfo_Kubernetes.DiscardUnknown(m)
}

var xxx_messageInfo_Kubernetes proto.InternalMessageInfo

func (m *Kubernetes) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type System struct {
	Architecture         string      `protobuf:"bytes,1,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Hostname             string      `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Platform             string      `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Container            *Container  `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	Kubernetes           *Kubernetes `protobuf:"bytes,5,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *System) Reset()         { *m = System{} }
func (m *System) String() string { return proto.CompactTextString(m) }
func (*System) ProtoMessage()    {}
func (*System) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{2}
}

func (m *System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_System.Unmarshal(m, b)
}
func (m *System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_System.Marshal(b, m, deterministic)
}
func (m *System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_System.Merge(m, src)
}
func (m *System) XXX_Size() int {
	return xxx_messageInfo_System.Size(m)
}
func (m *System) XXX_DiscardUnknown() {
	xxx_messageInfo_System.DiscardUnknown(m)
}

var xxx_messageInfo_System proto.InternalMessageInfo

func (m *System) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *System) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *System) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *System) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *System) GetKubernetes() *Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

func init() {
	proto.RegisterType((*Container)(nil), "model.Container")
	proto.RegisterType((*Kubernetes)(nil), "model.Kubernetes")
	proto.RegisterType((*System)(nil), "model.System")
}

func init() { proto.RegisterFile("system.proto", fileDescriptor_86a7260ebdc12f47) }

var fileDescriptor_86a7260ebdc12f47 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4e, 0xc4, 0x20,
	0x10, 0xc6, 0x43, 0x75, 0x37, 0x32, 0x6e, 0x8c, 0x72, 0x22, 0xea, 0x61, 0xc3, 0x69, 0xe3, 0x81,
	0x44, 0x7d, 0x04, 0x8f, 0xde, 0xea, 0x13, 0x50, 0x3a, 0xa6, 0xc4, 0x02, 0x0d, 0x4c, 0x0f, 0x3e,
	0xa1, 0xaf, 0x65, 0x8a, 0xfd, 0xe3, 0x1e, 0x67, 0xbe, 0xdf, 0x17, 0xf8, 0x0d, 0x1c, 0xf2, 0x77,
	0x26, 0xf4, 0x7a, 0x48, 0x91, 0xa2, 0xd8, 0xf9, 0xd8, 0x62, 0xaf, 0x1e, 0x80, 0xbf, 0xc5, 0x40,
	0xc6, 0x05, 0x4c, 0xe2, 0x06, 0x2a, 0xd7, 0x4a, 0x76, 0x64, 0x27, 0x5e, 0x57, 0xae, 0x55, 0x4f,
	0x00, 0xef, 0x63, 0x83, 0x29, 0x20, 0x61, 0x16, 0x8f, 0xc0, 0x83, 0xf1, 0x98, 0x07, 0x63, 0x71,
	0x86, 0xb6, 0x85, 0xfa, 0x61, 0xb0, 0xff, 0x28, 0x0f, 0x08, 0x05, 0x07, 0x93, 0x6c, 0xe7, 0x08,
	0x2d, 0x8d, 0x69, 0x61, 0xcf, 0x76, 0xe2, 0x1e, 0xae, 0xba, 0x98, 0x69, 0xea, 0xcb, 0xaa, 0xe4,
	0xeb, 0x3c, 0x65, 0x43, 0x6f, 0xe8, 0x33, 0x26, 0x2f, 0x2f, 0xfe, 0xb2, 0x65, 0x16, 0x1a, 0xb8,
	0x5d, 0xfe, 0x2b, 0x2f, 0x8f, 0xec, 0x74, 0xfd, 0x72, 0xab, 0x8b, 0x8a, 0x5e, 0x3d, 0xea, 0x0d,
	0x11, 0xcf, 0x00, 0x5f, 0xab, 0x82, 0xdc, 0x95, 0xc2, 0xdd, 0x5c, 0xd8, 0xdc, 0xea, 0x7f, 0x50,
	0xb3, 0x2f, 0x07, 0x7a, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x57, 0x9a, 0xdf, 0xc2, 0x30, 0x01,
	0x00, 0x00,
}
