// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tags.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/lyft/protoc-gen-validate/validate"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TagValue struct {
	NumberValue          float64  `protobuf:"fixed64,1,opt,name=number_value,json=numberValue,proto3" json:"number_value,omitempty"`
	StringValue          string   `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BoolValue            bool     `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagValue) Reset()         { *m = TagValue{} }
func (m *TagValue) String() string { return proto.CompactTextString(m) }
func (*TagValue) ProtoMessage()    {}
func (*TagValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d9cbcae1e528f6, []int{0}
}

func (m *TagValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagValue.Unmarshal(m, b)
}
func (m *TagValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagValue.Marshal(b, m, deterministic)
}
func (m *TagValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagValue.Merge(m, src)
}
func (m *TagValue) XXX_Size() int {
	return xxx_messageInfo_TagValue.Size(m)
}
func (m *TagValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TagValue.DiscardUnknown(m)
}

var xxx_messageInfo_TagValue proto.InternalMessageInfo

func (m *TagValue) GetNumberValue() float64 {
	if m != nil {
		return m.NumberValue
	}
	return 0
}

func (m *TagValue) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *TagValue) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func init() {
	proto.RegisterType((*TagValue)(nil), "model.TagValue")
}

func init() { proto.RegisterFile("tags.proto", fileDescriptor_e7d9cbcae1e528f6) }

var fileDescriptor_e7d9cbcae1e528f6 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x4c, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x91, 0x12, 0x2f,
	0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0x49, 0xd5, 0x87, 0x31, 0x20, 0xf2, 0x4a, 0xd5, 0x5c, 0x1c,
	0x21, 0x89, 0xe9, 0x61, 0x89, 0x39, 0xa5, 0xa9, 0x42, 0x8a, 0x5c, 0x3c, 0x79, 0xa5, 0xb9, 0x49,
	0xa9, 0x45, 0xf1, 0x65, 0x20, 0xbe, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x37, 0x44, 0x0c,
	0xa2, 0x44, 0x97, 0x8b, 0xa7, 0xb8, 0xa4, 0x28, 0x33, 0x2f, 0x1d, 0xaa, 0x84, 0x49, 0x81, 0x51,
	0x83, 0xd3, 0x89, 0x6b, 0xd7, 0xcb, 0x03, 0xcc, 0xac, 0x45, 0xcc, 0x12, 0x0d, 0x1c, 0x41, 0xdc,
	0x10, 0x79, 0x88, 0x72, 0x59, 0x2e, 0xae, 0xa4, 0xfc, 0xfc, 0x1c, 0xa8, 0x62, 0x66, 0x05, 0x46,
	0x0d, 0x8e, 0x20, 0x4e, 0x90, 0x08, 0x58, 0x3a, 0x89, 0x0d, 0xec, 0x06, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0x68, 0x6c, 0x3b, 0xb1, 0x00, 0x00, 0x00,
}
