// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tags.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on TagValue with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *TagValue) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for NumberValue

	if utf8.RuneCountInString(m.GetStringValue()) > 1024 {
		return TagValueValidationError{
			field:  "StringValue",
			reason: "value length must be at most 1024 runes",
		}
	}

	// no validation rules for BoolValue

	return nil
}

// TagValueValidationError is the validation error returned by
// TagValue.Validate if the designated constraints aren't met.
type TagValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagValueValidationError) ErrorName() string { return "TagValueValidationError" }

// Error satisfies the builtin error interface
func (e TagValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTagValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagValueValidationError{}
