// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TraceId              string               `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentId             string               `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Name                 string               `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Result               string               `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	Type                 string               `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Sampled              bool                 `protobuf:"varint,10,opt,name=sampled,proto3" json:"sampled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Transaction) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Transaction) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Transaction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Transaction) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Transaction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Transaction) GetSampled() bool {
	if m != nil {
		return m.Sampled
	}
	return false
}

func init() {
	proto.RegisterType((*Transaction)(nil), "model.Transaction")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xcd, 0x6a, 0xc3, 0x30,
	0x10, 0x84, 0xb1, 0x9b, 0xf8, 0x67, 0x03, 0x85, 0xee, 0xa1, 0x28, 0x2e, 0xb4, 0xa6, 0x27, 0x9f,
	0x1c, 0x68, 0x29, 0xf4, 0x01, 0x7a, 0xc9, 0xd5, 0xe4, 0x5e, 0x94, 0x48, 0x0d, 0x02, 0xcb, 0x12,
	0xf2, 0xfa, 0xd0, 0xb7, 0xe9, 0xa3, 0x16, 0xaf, 0xe3, 0x18, 0xda, 0xdb, 0xce, 0xcc, 0xc7, 0x68,
	0x04, 0x77, 0x14, 0x64, 0xd7, 0xcb, 0x13, 0x19, 0xd7, 0xd5, 0x3e, 0x38, 0x72, 0xb8, 0xb6, 0x4e,
	0xe9, 0xb6, 0x78, 0x3c, 0x3b, 0x77, 0x6e, 0xf5, 0x8e, 0xcd, 0xe3, 0xf0, 0xb5, 0x53, 0x43, 0x90,
	0x0b, 0x56, 0x3c, 0xfd, 0xcd, 0xc9, 0x58, 0xdd, 0x93, 0xb4, 0x7e, 0x02, 0x9e, 0x7f, 0x62, 0xd8,
	0x1c, 0x96, 0x76, 0x7c, 0x87, 0xfc, 0x8a, 0x88, 0xa8, 0x8c, 0xaa, 0xcd, 0x4b, 0x51, 0x4f, 0x25,
	0xf5, 0x5c, 0x52, 0x1f, 0x66, 0xa2, 0x59, 0x60, 0xbc, 0x85, 0xd8, 0x28, 0x11, 0x97, 0x51, 0x95,
	0x37, 0xb1, 0x51, 0xb8, 0x85, 0x8c, 0x82, 0x3c, 0xe9, 0x4f, 0xa3, 0xc4, 0x0d, 0xbb, 0x29, 0xeb,
	0xbd, 0xc2, 0x07, 0xc8, 0xbd, 0x0c, 0xba, 0xa3, 0x31, 0x5b, 0x71, 0x96, 0x4d, 0xc6, 0x5e, 0xe1,
	0x1b, 0x64, 0xf3, 0x27, 0xc4, 0x9a, 0x07, 0x6c, 0xff, 0x0d, 0xf8, 0xb8, 0x00, 0xcd, 0x15, 0x45,
	0x84, 0x55, 0x27, 0xad, 0x16, 0x09, 0xd7, 0xf1, 0x8d, 0xf7, 0x90, 0x04, 0xdd, 0x0f, 0x2d, 0x89,
	0x94, 0xdd, 0x8b, 0x1a, 0x59, 0xfa, 0xf6, 0x5a, 0x64, 0x13, 0x3b, 0xde, 0x28, 0x20, 0xed, 0xa5,
	0xf5, 0xad, 0x56, 0x02, 0xca, 0xa8, 0xca, 0x9a, 0x59, 0x1e, 0x13, 0x7e, 0xf6, 0xf5, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xbb, 0xc1, 0xe7, 0x6a, 0x86, 0x01, 0x00, 0x00,
}
