// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: transaction.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Transaction with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Transaction) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetId()) < 1 {
		return TransactionValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetTraceId()) < 1 {
		return TransactionValidationError{
			field:  "TraceId",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for ParentId

	if v, ok := interface{}(m.GetSpanCount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "SpanCount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetDuration() == nil {
		return TransactionValidationError{
			field:  "Duration",
			reason: "value is required",
		}
	}

	// no validation rules for Name

	// no validation rules for Result

	if utf8.RuneCountInString(m.GetType()) < 1 {
		return TransactionValidationError{
			field:  "Type",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for Marks

	// no validation rules for Sampled

	return nil
}

// TransactionValidationError is the validation error returned by
// Transaction.Validate if the designated constraints aren't met.
type TransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionValidationError) ErrorName() string { return "TransactionValidationError" }

// Error satisfies the builtin error interface
func (e TransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionValidationError{}

// Validate checks the field values on Transaction_SpanCount with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *Transaction_SpanCount) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Started

	// no validation rules for Dropped

	return nil
}

// Transaction_SpanCountValidationError is the validation error returned by
// Transaction_SpanCount.Validate if the designated constraints aren't met.
type Transaction_SpanCountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Transaction_SpanCountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Transaction_SpanCountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Transaction_SpanCountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Transaction_SpanCountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Transaction_SpanCountValidationError) ErrorName() string {
	return "Transaction_SpanCountValidationError"
}

// Error satisfies the builtin error interface
func (e Transaction_SpanCountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransaction_SpanCount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Transaction_SpanCountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Transaction_SpanCountValidationError{}
